// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zachariasz_Jankowski.Data;

namespace Zachariasz_Jankowski.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20191225161814_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("Zachariasz_Jankowski.Models.Test", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<int>("post")
                        .HasColumnType("INTEGER");

                    b.HasKey("username", "post");

                    b.ToTable("test");
                });
#pragma warning restore 612, 618
        }
    }
}
